### PR TITLE
Add connection/channel management

### PR DESCRIPTION
**Pull request by gingermusketeer**
Needs a bit of styling.

It would be good to get some feedback on what i have done so far.

### CODE REVIEW

**Comment by enwin** [comment]
Nice start!

I'm have an issue with adding one more channel or connection. You have to save your current configuration before adding some more or all the settings not saved are lost as it reload the DOM.

Count me in for some styling if you need!

**Comment by gingermusketeer** [comment]
@enwin Thanks for the feedback! I will try and refine it soon

**Comment by tj** [comment]
cool nice start :D I think I had styling for this in a branch actually, just didn't implement the actual setting functionality, but the screenshot in the Readme is what it looked like. I'll see if I can grab that later

**Comment by tj** [comment]
nvm I lost that branch :D

**Comment by gingermusketeer** [comment]
@enwin @visionmedia I have made a few changes to the behaviour of the settings page. It now adds connections and channels without re-rendering the dialog. 

@enwin If you have some time to do some styling that would be great.

**Comment by mkody** [comment]
Hello, isn't it better to "protect" a bit more the password? :D 

6stu5

**Comment by gingermusketeer** [comment]
@mkody I will change that to a password field

**Comment by enwin** [comment]
@gingermusketeer and I added some styling on the page.
slate-connection-settings

The password field is also updated to a reall `input[type=password]`

**Comment by brandly** [comment]
What needs to happen to get this merged?

**Comment by frdmn** [comment]
:+1:

**Comment by hhsnopek** [comment]
:+1:

**Comment by yasoob** [comment]
:+1:

**Comment by jeremybarbet** [comment]
:+1:

**Comment by hunterboerner** [comment]
Status?

**Comment by gingermusketeer** [comment]
@hunterboerner I would suggest looking at alternatives. I am using [erming/shout](/erming/shout) which i quite like (uses some of the modules from slate) Or you could try [mephux/komanda](/mephux/komanda)

**Comment by gingermusketeer** [comment]
Looks like this is not going to happen. closing

**Pull request closed without merging**
